# Generated by Django 4.1.5 on 2023-01-08 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 9, 6, 38, 52, 583625)),
        ),
        migrations.AddField(
            model_name='template',
            name='female_name',
            field=models.CharField(default='default', max_length=40),
        ),
        migrations.AddField(
            model_name='template',
            name='id_global',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='id_template',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='male_name',
            field=models.CharField(default='default', max_length=4),
        ),
    ]
