# Generated by Django 4.1.5 on 2023-02-07 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 8, 5, 32, 53, 301874)),
        ),
        migrations.AlterField(
            model_name='template_event',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2023, 2, 8, 5, 32, 53, 301874)),
        ),
        migrations.AlterField(
            model_name='template_event',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 2, 8, 5, 32, 53, 301874)),
        ),
    ]
