# Generated by Django 4.1.5 on 2023-02-07 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_template_date_alter_template_event_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 8, 5, 44, 33, 801944)),
        ),
        migrations.AlterField(
            model_name='template',
            name='owner',
            field=models.CharField(default='default', max_length=40),
        ),
        migrations.AlterField(
            model_name='template_event',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2023, 2, 8, 5, 44, 33, 801944)),
        ),
        migrations.AlterField(
            model_name='template_event',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 2, 8, 5, 44, 33, 801944)),
        ),
    ]
