# Generated by Django 4.1.5 on 2023-01-18 03:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0002_template_date_template_female_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='owner',
        ),
        migrations.AddField(
            model_name='template',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 10, 54, 2, 551667)),
        ),
    ]
