# Generated by Django 4.1.5 on 2023-01-18 12:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_template_owner_template_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='user',
        ),
        migrations.AddField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='members.accountdb'),
        ),
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 19, 16, 57, 677903)),
        ),
    ]
