# Generated by Django 4.1.5 on 2023-01-27 00:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_template_user_template_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 27, 7, 56, 5, 799547)),
        ),
        migrations.CreateModel(
            name='Template_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='default', max_length=40)),
                ('description', models.CharField(default='default', max_length=200)),
                ('date_start', models.DateField(default=datetime.datetime(2023, 1, 27, 7, 56, 5, 799547))),
                ('date_end', models.DateField(default=datetime.datetime(2023, 1, 27, 7, 56, 5, 799547))),
                ('address', models.CharField(default='default', max_length=200)),
                ('template_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='members.template')),
            ],
        ),
    ]
