# Generated by Django 4.1.5 on 2023-02-05 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_template_date_template_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 6, 5, 45, 10, 133323)),
        ),
        migrations.AlterField(
            model_name='template_event',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2023, 2, 6, 5, 45, 10, 134324)),
        ),
        migrations.AlterField(
            model_name='template_event',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 2, 6, 5, 45, 10, 134324)),
        ),
        migrations.AlterField(
            model_name='template_event',
            name='template_id',
            field=models.IntegerField(default=0),
        ),
    ]
