# Generated by Django 4.1.5 on 2023-02-06 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_template_date_alter_template_event_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 6, 14, 56, 57, 114629)),
        ),
        migrations.AlterField(
            model_name='template_event',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2023, 2, 6, 14, 56, 57, 115629)),
        ),
        migrations.AlterField(
            model_name='template_event',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 2, 6, 14, 56, 57, 115629)),
        ),
    ]
